name: test-all
on:
    push:
        branches:
            - develop
            - main
        paths:
            - "packages/**"
            - ".github/workflows/**"
            - "package.json"
            - "!**.md"
    pull_request:
        branches:
            - develop
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ">=14.6.0"
            - run: |
                  yarn bootstrap
                  sed -i'' -e 's/readonly url: string/url: string/' node_modules/@types/snowpack-env/index.d.ts
                  node_modules/.bin/lerna run build --sort
                  yarn test:only
